apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: default
type: Opaque
stringData:
  AUTH: "mongodb+srv://sujitku5619_db_user:LpDdryzprwpUnTvH@cluster0.qk7jmjv.mongodb.net/auth"
  AUTH_MONGO_URI: "mongodb+srv://sujitku5619_db_user:LpDdryzprwpUnTvH@cluster0.qk7jmjv.mongodb.net/auth"
  AI: "mongodb+srv://sujitku5619_db_user:LpDdryzprwpUnTvH@cluster0.qk7jmjv.mongodb.net/ai"
  SANDBOX: "mongodb+srv://sujitku5619_db_user:LpDdryzprwpUnTvH@cluster0.qk7jmjv.mongodb.net/sandbox"
  REDIS_URI: "redis://default:5uYvLM89tL1Js9Do27MRjFbvlxKid6iw@redis-12428.crce206.ap-south-1-1.ec2.cloud.redislabs.com:12428"
  EMAIL_USER: "sujitku5619@gmail.com"

---
apiVersion: v1
kind: Secret
metadata:
  name: google
  namespace: default
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "733760618590-16i14hdk8hnbgig5a0j2qabugln2adn8.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_REFRESH_TOKEN: "TOKEN=1//04UJVU3qMemPHCgYIARAAGAQSNwF-L9IrdJG5zWwbl7stFS8NS31r84yKEwBGVEzHnMWcFI8arKcN12t__de3tP4jEGQEC9qR5Ho"
  EMAIL_APP_PASSWORD: "eaxmgnauclhpjcez"

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
  namespace: default
type: Opaque
stringData:
  AUTH_JWT_SECRET: "566d2a9756a682eb3cdd122b8ff5af513a65e3420c6bc3a1aa348cf0258cac6d"

---
apiVersion: v1
kind: Secret

metadata:
  name: amqlib
  namespace: default
type: Opaque
stringData:
  RABBITMQ_URL: "amqps://ubdptgby:v8K95q4zY5M1e_w7F54e-zLpTWErG07c@gull.rmq.cloudamqp.com/ubdptgby"
  RABBITMQ_PORT: "5672"
  EMAIL_USER: "sujitku5619@gmail.com"

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: default
type: Opaque
stringData:
  MISTRALAI_API_KEY: "x8WFHFJI8f2cmJqvvHFkfpX93rHue0mU"

---  