apiVersion: v1
kind: Secret
metadata:
    name: database
type: Opaque
stringData:
    AUTH: "mongodb+srv://sujitku5619_db_user:LpDdryzprwpUnTvH@cluster0.qk7jmjv.mongodb.net/auth"
    AI: "mongodb+srv://sujitku5619_db_user:LpDdryzprwpUnTvH@cluster0.qk7jmjv.mongodb.net/ai"
    SANDBOX: "mongodb+srv://sujitku5619_db_user:LpDdryzprwpUnTvH@cluster0.qk7jmjv.mongodb.net/sandbox"


---

apiVersion: v1
kind: Secret
metadata:
    name: google
type: Opaque
stringData:
    GOOGLE_CLIENT_ID: "33760618590-16i14hdk8hnbgig5a0j2qabugln2adn8.apps.googleusercontent.com"
    GOOGLE_CLIENT_SECRET: "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"

---

apiVersion: v1
kind: Secret
metadata:
    name: jwt
type: Opaque
stringData:
    AUTH_JWT_SECRET: "566d2a9756a682eb3cdd122b8ff5af513a65e3420c6bc3a1aa348cf0258cac6d"


---


apiVersion: v1
kind: Secret
metadata:
    name: ai-secrets
type: Opaque
stringData:
    MISTRALAI_API_KEY: "x8WFHFJI8f2cmJqvvHFkfpX93rHue0mU"
