import {START,StateGraph,StateSchema,END, type GraphNode,type CompiledStateGraph } from "@langchain/langgraph"
import z from "zod";
import {GoogleAI,MistralAI,CohereAI} from "./model.ai.js";
import {createAgent,HumanMessage,providerStrategy} from "langchain"


const state = new StateSchema({
    problem: z.string(),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judgement: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
});



const solutionNode: GraphNode <typeof state> = async(state) =>{

    const [mistralResponse,cohereResponse] = await Promise.all([
        MistralAI.invoke(state.problem),
        CohereAI.invoke(state.problem)
    ]);

    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    }
}



const judgeNode: GraphNode <typeof state> = async(state) =>{

    const {problem,solution_1,solution_2} = state;

    const judge = createAgent({
        model: GoogleAI,
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_1_reasoning: z.string().default(""),
            solution_2_reasoning: z.string().default(""),
        })),

        systemPrompt: `You are a judge tasked with evaluating two solutions generated by two different AI models to the following problem: ${problem}. Please provide a score between 0 and 10 for each solution, along with your reasoning for the score.`
    }) 

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please provide your evaluation in the specified format.`)
        ]
    });

    const {solution_1_score,solution_2_score,solution_1_reasoning,solution_2_reasoning} = judgeResponse.structuredResponse;

    return {
        judgement: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    };

}


const graph = new StateGraph(state)
    .addNode("solutionNode",solutionNode)
    .addNode("judgeNode",judgeNode)
    .addEdge(START,"solutionNode")
    .addEdge("solutionNode","judgeNode")
    .addEdge("judgeNode",END)
    .compile();


    export default async function (problem: string) {

        const response = await graph.invoke({
            problem: problem
        })

        return response;

    }